In [1]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6])
print('A is of type:', type(a))
print('Print the entire array:', a)
print('Print the first value:', a[0])
print('Print the first three value:', a[0:3])
print('Print from second value till end  of list:', a[2:])
print('Print the last value of a numpy array:', a[-1])
print('Print up till the 2nd to last value:', a[:-2]) 

A is of type: <class 'numpy.ndarray'>
Print the entire array: [0 1 2 3 4 5 6]
Print the first value: 0
Print the first three value: [0 1 2]
Print from second value till end  of list: [2 3 4 5 6]
Print the last value of a numpy array: 6
Print up till the 2nd to last value: [0 1 2 3 4]


In [28]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])

# Multiplication
b1 = 10 * a                  # Direct multiplication by 10
b2 = np.multiply(10, a)      # Alternative way using np.multiply

# Addition
c1 = a + b1                  # Direct addition
c2 = np.add(a, b1)           # Alternative way using np.add

# Subtraction
sub1 = a - 2                 # Direct subtraction of 2 from each element
sub2 = np.subtract(a, 2)     # Alternative way using np.subtract

# Division
div1 = a / 2                 # Direct division by 2
div2 = np.divide(a, 2)       # Alternative way using np.divide

# Logarithm (natural log)
d = np.log(a)                # Logarithm for scaling or normalization

# Square root
e = np.sqrt(a)               # Square root of each element

# Squaring each element
f = a ** 2                   # Squaring using exponent
g = np.square(a)             # Alternative using np.square

# Printing results
print('Array a:', a)
print('Multiplication results b1:', b1)
print('Multiplication results b2:', b2)
print('Addition results c1:', c1)
print('Addition results c2:', c2)
print('Subtraction results sub1:', sub1)
print('Subtraction results sub2:', sub2)
print('Division results div1:', div1)
print('Division results div2:', div2)
print('Logarithm result d:', d)
print('Square root result e:', e)
print('Squared result f:', f)
print('Squared result using np.square:', g)



Array a: [1 2 3 4 5 6]
Multiplication results b1: [10 20 30 40 50 60]
Multiplication results b2: [10 20 30 40 50 60]
Addition results c1: [11 22 33 44 55 66]
Addition results c2: [11 22 33 44 55 66]
Subtraction results sub1: [-1  0  1  2  3  4]
Subtraction results sub2: [-1  0  1  2  3  4]
Division results div1: [0.5 1.  1.5 2.  2.5 3. ]
Division results div2: [0.5 1.  1.5 2.  2.5 3. ]
Logarithm result d: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Square root result e: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Squared result f: [ 1  4  9 16 25 36]
Squared result using np.square: [ 1  4  9 16 25 36]


In [13]:
import numpy as np
a = np.arange(15) 
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [17]:

a = np.arange( 0, 15, 1 ) #Alternate specification with np.arrange(start, end, step)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
a=a.reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
b= np.ones(shape=(3, 5), dtype=float)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
c= np.zeros(shape=(3, 5), dtype=int)
print(c)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [21]:
d= np.full((3, 5), 4, dtype=int)
print(d)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [22]:
e= np.arange( 0, 1.5, .1 ).reshape(3,5)  #String together creations and reshaping. Also can use decimals.
print(e)

[[0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4]]


In [23]:
np.random.seed([2335])
a = np.random.uniform(50, 150, 10)  #Between 50-150, generate 10 variables from uniform
b = np.random.standard_normal(10)   #With mean 0 and standard deviation 1 
print(a)
print(b)

[109.46519698  50.85780228 145.64145344  78.97269151  92.70351313
  52.40115672 100.85344015 136.72543799  97.50815861  65.22120624]
[-0.78579231  0.47561356 -1.03844076  1.22334432 -2.21874131 -0.71922972
  0.22159424 -1.00226326  0.07889796 -1.00275058]


In [24]:
a = np.arange(5)
b=np.concatenate([a,a])
c=np.vstack([a,a])
d=np.hstack([c,c])
print('a:',a,'\nb:',b,'\nc:',c,'\nd:',d)

a: [0 1 2 3 4] 
b: [0 1 2 3 4 0 1 2 3 4] 
c: [[0 1 2 3 4]
 [0 1 2 3 4]] 
d: [[0 1 2 3 4 0 1 2 3 4]
 [0 1 2 3 4 0 1 2 3 4]]


## Read and Store Each Row, Convert to a NumPy Array

In [35]:
import pandas as pd

# Load the CSV file using the correct path
data = pd.read_csv('./extended_student_exam_prediction_dataset.csv')

# Display the first few rows to confirm it's loaded correctly
print(data.head())


   Study Hours  Previous Grades  ...  Extracurriculars  Pass
0           10               85  ...                 1     1
1            7               70  ...                 2     1
2            4               60  ...                 0     0
3            5               75  ...                 1     1
4            3               50  ...                 1     0

[5 rows x 6 columns]


## Get directory name and list file in directory

In [34]:
import os

# List all files in the current directory and subdirectories
for root, dirs, files in os.walk("."):
    for file in files:
        print(os.path.join(root, file))


./extended_student_exam_prediction_dataset.csv
./notebook.ipynb


## Convert the list of lists to a NumPy array

In [36]:
import numpy as np
import csv

# Open and read the CSV file with the correct path
csv_file_object = csv.reader(open('extended_student_exam_prediction_dataset.csv', newline=''), delimiter=',')

# Initialize an empty list to store the data
data = []

# Read the header row (to skip it) and store it if needed
header = next(csv_file_object)

# Loop through each row in the CSV file and append to the data list
for row in csv_file_object:  
    data.append(row)  # Add each row to the data list

# Convert the list of lists to a NumPy array
data = np.array(data)

# Print the NumPy array
print("Data as NumPy array:\n", data)


Data as NumPy array:
 [['10' '85' '90' '7' '1' '1']
 ['7' '70' '85' '6' '2' '1']
 ['4' '60' '60' '5' '0' '0']
 ['5' '75' '80' '7' '1' '1']
 ['3' '50' '65' '6' '1' '0']
 ['8' '80' '90' '8' '2' '1']
 ['6' '65' '70' '5' '0' '0']
 ['9' '80' '88' '6' '2' '1']
 ['2' '55' '50' '5' '1' '0']
 ['7' '78' '85' '7' '1' '1']
 ['6' '73' '72' '6' '1' '0']
 ['5' '70' '60' '5' '0' '0']
 ['9' '95' '95' '8' '2' '1']
 ['3' '40' '55' '6' '0' '0']
 ['8' '65' '75' '7' '1' '1']
 ['5' '78' '88' '6' '1' '1']
 ['7' '85' '82' '7' '2' '1']
 ['6' '72' '68' '6' '0' '0']
 ['4' '65' '60' '5' '1' '0']
 ['10' '88' '92' '8' '2' '1']]


## Convert the first five columns to float for analysis

In [41]:
import numpy as np
import csv


# Separate the first five columns (numerical data) and the last column (label)
study_data = data[:, 0:5].astype(np.float_)  # Convert the first five columns to float for analysis
pass_label = data[:, 5]                      # Select only the last column for label

# Print the separated arrays for verification
print("Study Data (first five columns):\n", study_data)
print("\nPass Label (last column):\n", pass_label)


# Sum up the values of the first column (Study Hours)
sum_study_hours = study_data[:, 0].sum()
print("\nSum of Study Hours:", sum_study_hours)

# Extract the first column (Study Hours) and assign it to a new variable
study_hours = study_data[:, 0]

# Display the extracted column
print("\nStudy Hours (first column):\n", study_hours)


Study Data (first five columns):
 [[10. 85. 90.  7.  1.]
 [ 7. 70. 85.  6.  2.]
 [ 4. 60. 60.  5.  0.]
 [ 5. 75. 80.  7.  1.]
 [ 3. 50. 65.  6.  1.]
 [ 8. 80. 90.  8.  2.]
 [ 6. 65. 70.  5.  0.]
 [ 9. 80. 88.  6.  2.]
 [ 2. 55. 50.  5.  1.]
 [ 7. 78. 85.  7.  1.]
 [ 6. 73. 72.  6.  1.]
 [ 5. 70. 60.  5.  0.]
 [ 9. 95. 95.  8.  2.]
 [ 3. 40. 55.  6.  0.]
 [ 8. 65. 75.  7.  1.]
 [ 5. 78. 88.  6.  1.]
 [ 7. 85. 82.  7.  2.]
 [ 6. 72. 68.  6.  0.]
 [ 4. 65. 60.  5.  1.]
 [10. 88. 92.  8.  2.]]

Pass Label (last column):
 ['1' '1' '0' '1' '0' '1' '0' '1' '0' '1' '0' '0' '1' '0' '1' '1' '1' '0'
 '0' '1']

Sum of Study Hours: 124.0

Study Hours (first column):
 [10.  7.  4.  5.  3.  8.  6.  9.  2.  7.  6.  5.  9.  3.  8.  5.  7.  6.
  4. 10.]


## Basic Statistics (Mean, Sum, Standard Deviation)

In [42]:
# Mean of each feature
mean_study_hours = study_data[:, 0].mean()
mean_previous_grades = study_data[:, 1].mean()

print("Mean Study Hours:", mean_study_hours)
print("Mean Previous Grades:", mean_previous_grades)

# Standard deviation of Attendance Rate
std_attendance = study_data[:, 2].std()
print("Standard Deviation of Attendance Rate:", std_attendance)


Mean Study Hours: 6.2
Mean Previous Grades: 71.45
Standard Deviation of Attendance Rate: 13.470337783441067


## Conditional Selection

- Use conditions to filter data. For example, find students who studied more than 8 hours or had high attendance rates.
- This is useful for identifying students who meet certain performance thresholds.

In [40]:
# Select students who studied more than 8 hours
high_study_hours = study_data[study_data[:, 0] > 8]

# Select students with Attendance Rate above 85
high_attendance = study_data[study_data[:, 2] > 85]

print("Students with high study hours:\n", high_study_hours)
print("Students with high attendance rates:\n", high_attendance)


Students with high study hours:
 [[10. 85. 90.  7.  1.]
 [ 9. 80. 88.  6.  2.]
 [ 9. 95. 95.  8.  2.]
 [10. 88. 92.  8.  2.]]
Students with high attendance rates:
 [[10. 85. 90.  7.  1.]
 [ 8. 80. 90.  8.  2.]
 [ 9. 80. 88.  6.  2.]
 [ 9. 95. 95.  8.  2.]
 [ 5. 78. 88.  6.  1.]
 [10. 88. 92.  8.  2.]]


## Normalization and Standardization

- Normalization: Rescale each feature to a range between 0 and 1. Useful when features have different ranges, like Study Hours vs. Attendance Rate.
- Standardization: Scale features to have a mean of 0 and standard deviation of 1. Useful for preparing data for machine learning.

In [44]:
# Normalization (scales values between 0 and 1)
normalized_study_hours = study_data[:, 0] / study_data[:, 0].max()
normalized_previous_grades = study_data[:, 1] / study_data[:, 1].max()

print("Normalized Study Hours:\n", normalized_study_hours)
print("Normalized Previous Grades:\n", normalized_previous_grades)

# Standardization (scales values to have a mean of 0 and standard deviation of 1)
standardized_study_hours = (study_data[:, 0] - study_data[:, 0].mean()) / study_data[:, 0].std()
print("Standardized Study Hours:\n", standardized_study_hours)


Normalized Study Hours:
 [1.  0.7 0.4 0.5 0.3 0.8 0.6 0.9 0.2 0.7 0.6 0.5 0.9 0.3 0.8 0.5 0.7 0.6
 0.4 1. ]
Normalized Previous Grades:
 [0.89473684 0.73684211 0.63157895 0.78947368 0.52631579 0.84210526
 0.68421053 0.84210526 0.57894737 0.82105263 0.76842105 0.73684211
 1.         0.42105263 0.68421053 0.82105263 0.89473684 0.75789474
 0.68421053 0.92631579]
Standardized Study Hours:
 [ 1.65687874  0.34881658 -0.95924558 -0.52322486 -1.3952663   0.7848373
 -0.08720414  1.22085802 -1.83128702  0.34881658 -0.08720414 -0.52322486
  1.22085802 -1.3952663   0.7848373  -0.52322486  0.34881658 -0.08720414
 -0.95924558  1.65687874]


## Correlation between Features

In [45]:
# Correlation between Study Hours and Previous Grades
correlation = np.corrcoef(study_data[:, 0], study_data[:, 1])[0, 1]
print("Correlation between Study Hours and Previous Grades:", correlation)


Correlation between Study Hours and Previous Grades: 0.8185594196706354


## Adding New Features (Feature Engineering)

Example: Create a new feature that represents the “engagement level,” combining Study Hours, Attendance Rate, and Extracurriculars. This can help provide a summary score for each student’s involvement.

In [46]:
# Engagement level as a weighted combination of Study Hours, Attendance Rate, and Extracurriculars
engagement_level = 0.5 * study_data[:, 0] + 0.3 * study_data[:, 2] + 0.2 * study_data[:, 4]
print("Engagement Level for each student:\n", engagement_level)


Engagement Level for each student:
 [32.2 29.4 20.  26.7 21.2 31.4 24.  31.3 16.2 29.2 24.8 20.5 33.4 18.
 26.7 29.1 28.5 23.4 20.2 33. ]


## Categorizing Students by Performance with Conditional Slicing

In [47]:
# Define categories based on Study Hours
high_performers = study_data[study_data[:, 0] >= 8]  # Study hours >= 8
average_performers = study_data[(study_data[:, 0] < 8) & (study_data[:, 0] >= 5)]
low_performers = study_data[study_data[:, 0] < 5]

print("High Performers:\n", high_performers)
print("Average Performers:\n", average_performers)
print("Low Performers:\n", low_performers)


High Performers:
 [[10. 85. 90.  7.  1.]
 [ 8. 80. 90.  8.  2.]
 [ 9. 80. 88.  6.  2.]
 [ 9. 95. 95.  8.  2.]
 [ 8. 65. 75.  7.  1.]
 [10. 88. 92.  8.  2.]]
Average Performers:
 [[ 7. 70. 85.  6.  2.]
 [ 5. 75. 80.  7.  1.]
 [ 6. 65. 70.  5.  0.]
 [ 7. 78. 85.  7.  1.]
 [ 6. 73. 72.  6.  1.]
 [ 5. 70. 60.  5.  0.]
 [ 5. 78. 88.  6.  1.]
 [ 7. 85. 82.  7.  2.]
 [ 6. 72. 68.  6.  0.]]
Low Performers:
 [[ 4. 60. 60.  5.  0.]
 [ 3. 50. 65.  6.  1.]
 [ 2. 55. 50.  5.  1.]
 [ 3. 40. 55.  6.  0.]
 [ 4. 65. 60.  5.  1.]]


## Matrix Operations for Advanced Calculations


- For advanced analysis, you could use matrix operations to calculate weighted scores, or perform matrix multiplication to model data interactions.
- Example: Calculate a weighted score matrix where each feature has a different impact on the "Pass" prediction.

In [48]:
# Define weights for each feature (Study Hours, Previous Grades, Attendance Rate, etc.)
weights = np.array([0.4, 0.3, 0.2, 0.05, 0.05])

# Calculate weighted score for each student
weighted_scores = np.dot(study_data, weights)
print("Weighted Scores for each student:\n", weighted_scores)


Weighted Scores for each student:
 [47.9  41.2  31.85 40.9  29.55 45.7  36.15 45.6  27.6  43.6  39.05 35.25
 51.6  24.5  38.1  43.35 45.15 37.9  33.4  49.3 ]


## Unique and Counting Occurrences

- Use np.unique to find unique values and their counts in a column (e.g., number of students participating in extracurriculars).
- This is helpful for categorical analysis.

In [49]:
# Count the number of students in each category of Extracurriculars (0, 1, or 2)
extracurricular_counts = np.unique(study_data[:, 4], return_counts=True)
print("Extracurricular Participation Counts:", extracurricular_counts)


Extracurricular Participation Counts: (array([0., 1., 2.]), array([5, 9, 6]))


## Stacking Arrays to Add New Columns

In [50]:
# Stack engagement_level as a new column in the study_data array
study_data_with_engagement = np.hstack((study_data, engagement_level.reshape(-1, 1)))
print("Study Data with Engagement Level:\n", study_data_with_engagement)


Study Data with Engagement Level:
 [[10.  85.  90.   7.   1.  32.2]
 [ 7.  70.  85.   6.   2.  29.4]
 [ 4.  60.  60.   5.   0.  20. ]
 [ 5.  75.  80.   7.   1.  26.7]
 [ 3.  50.  65.   6.   1.  21.2]
 [ 8.  80.  90.   8.   2.  31.4]
 [ 6.  65.  70.   5.   0.  24. ]
 [ 9.  80.  88.   6.   2.  31.3]
 [ 2.  55.  50.   5.   1.  16.2]
 [ 7.  78.  85.   7.   1.  29.2]
 [ 6.  73.  72.   6.   1.  24.8]
 [ 5.  70.  60.   5.   0.  20.5]
 [ 9.  95.  95.   8.   2.  33.4]
 [ 3.  40.  55.   6.   0.  18. ]
 [ 8.  65.  75.   7.   1.  26.7]
 [ 5.  78.  88.   6.   1.  29.1]
 [ 7.  85.  82.   7.   2.  28.5]
 [ 6.  72.  68.   6.   0.  23.4]
 [ 4.  65.  60.   5.   1.  20.2]
 [10.  88.  92.   8.   2.  33. ]]
